name: pel-manager-release

on:
  workflow_dispatch:
    inputs:
      release_job:
        description: "platform to build and publish"
        type: choice
        default: "all"
        options:
          - "all"
          - "setup"
          - "linux_arm64"
          - "linux_x8664"
          - "macos_arm64"
          - "macos_x8664"
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

jobs:
  setup:
    runs-on: ubuntu-latest

    if: ${{ contains(fromJSON('["", "all", "setup"]'), inputs.release_job) && github.actor != 'peldroid[bot]' }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Publish
        run: just publish-setup

  linux_arm64:
    runs-on: ubuntu-24.04-arm

    if: ${{ contains(fromJSON('["", "all", "linux_arm64"]'), inputs.release_job) && github.actor != 'peldroid[bot]' }}

    concurrency:
      group: linux_arm64
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish-bin

  linux_x8664:
    runs-on: ubuntu-latest

    if: ${{ contains(fromJSON('["", "all", "linux_x8664"]'), inputs.release_job) && github.actor != 'peldroid[bot]' }}

    concurrency:
      group: linux_x8664
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish-bin

  macos_arm64:
    runs-on: macos-latest

    if: ${{ contains(fromJSON('["", "all", "macos_arm64"]'), inputs.release_job) && github.actor != 'peldroid[bot]' }}

    concurrency:
      group: macos_arm64
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish-bin

  macos_x8664:
    runs-on: macos-15-intel

    if: ${{ contains(fromJSON('["", "all", "pkg_macos_x8664"]'), inputs.release_job) && github.actor != 'peldroid[bot]' }}

    concurrency:
      group: macos_x8664
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish-bin